name: Lint forwardauth source

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: eslint-cache
        uses: actions/cache/restore@v4
        with:
          path: .eslintcache
          key: eslint-${{ runner.os }}-${{ hashFiles('package-lock.json', 'eslint.config.*') }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Run ESLint
        id: lint
        run: |
          REPORT=$(npx eslint . -f json --max-warnings=0 --cache)
          COUNT=$(echo "$REPORT" | jq 'length')
          echo "::notice::ESLint OK - $COUNT files checked"

      - name: Save ESLint cache
        uses: actions/cache/save@v4
        if: steps.eslint-cache.outputs.cache-hit != 'true'
        with:
          path: .eslintcache
          key: eslint-${{ runner.os }}-${{ hashFiles('package-lock.json', 'eslint.config.*') }}
