name: Lint forwardauth source

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Run ESLint
        id: lint
        run: | 
          npx eslint . --max-warnings=0 --format json --output-file eslint-report.json
          jq '. | length' eslint-report.json | \
            awk '{print "::notice::Checked " $1 " files with ESLint"}'
          